### ISSUE TITLE
Unity 9 slicing utility. I want to buy the code.

### ISSUE THREAD

**Issue by AssisrMatheus** [phillyai/portfolio#1]
Hello, my name is Matheus and I'm working on a unity project

I saw your video about the 9 slice utility https://www.youtube.com/watch?v=PgSg7U1UVt0

And I wonder how you did this, I really need to do something similar. I'm willing to pay 100 US dollars for the source code of that. Hope you get in touch with me.

I tried sending an e-mail to 2@0chan.dev but it didn't work.

Please get in touch with me in my e-mail: `adowtatepmar@gmail.com` or add me in discord `assisrMatheus#2840`

Thank you!

**Comment by 20chan** [comment]
Thank you for your attention, I just open sources this program.
https://github.com/20chan/Mesh27Slice

**Comment by AssisrMatheus** [comment]
Thank you thank you thank you so much!!! 🤗🤗
